[package]
name = "rustacene"
version = "0.1.0"
edition = "2024"
build = "src/build.rs"

[dependencies]
bevy = "0.16"
rand = "0.9.1"
ndarray = "0.16.1"
petgraph = "0.8.1"
num-traits = "0.2.19"

[profile.release]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3