[package]
name = "rustacene"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.10.1"
rand = "0.8.5"
ndarray = "0.15.6"
petgraph = "0.6.2"
num-traits = "0.2.15"

[profile.dev.package."*"]
opt-level = 3